### ISSUE TITLE
Agenda for 1st AllERCDevs Meetup 2023-05-16 UTC2300

### ISSUE THREAD

**Issue by xinbenlv** [ercref/AllERCDevs#1]
Hi all, as per our time poll, we will have our first AllERCDevs Meetup on 
*2023-05-16 UTC 2300-2359 Tuesday*, which translates to
 
- 19:00-19:59 on 2023-05-16 Tuesday in US Eastern Time.
- 07:00-07:59 on 2023-05-17 Wednesday in Singapore.
- 16:00-16:59 on 2023-05-16 Tuesday in US Pacific Time.

The event will be hosted on Zoom, a link will also be posted on "all-erc-devs" channel on this [Discord Server](https://discord.gg/2arW34S6J7)

Join Zoom Meeting
https://us02web.zoom.us/j/84199236232?pwd=d3NjcC9xSlA5RHZjdnQ0YzBrNXVaQT09

Meeting ID: 841 9923 6232
Passcode: 532114

Agenda will be updated and please feel free to comment to signup your agenda items.

### Main Session (1h)

1. [ ] (15-20min) *Featured Talk*:  How EIP program started and why it matters, by Hudson Jameson (@Souptacular) 
2. (10min) *Demo Show & Tell* (5-10min per slot) 
- [ ] (5m)  [TurboEth](https://www.turboeth.xyz/) by @kamescg -> to be rescheduled, time TBD
- [ ] (5m)[HexLink](https://hexlink.io/) by @pette1999 -> to be rescheduled to [Session 2](#2)
4. (30min) *ERC Peer Review Requests* (5-10min per slot)
- [ ] (5-10m) [ERC-6982 Efficient Default Lockable NFTs](https://github.com/ethereum/EIPs/blob/82372cbae88746c496ce1fbd4524862606de7421/EIPS/eip-6982.md) and [EIP6454](https://eips.ethereum.org/EIPS/eip-6454) by @sullof
- [x] (5-10m) [ERC-7007 zkML AIGC NFTs](https://github.com/ethereum/EIPs/pull/7007) by @socathie
- [x] (5-10m) [ERC-6900](https://github.com/ethereum/EIPs/pull/6900) by @jwindawi
- [ ] (5-10m) [ERC-5269 ERC Discovery Interface](https://eips.ethereum.org/EIPS/eip-5269) by @xinbenlv

### Social Hour (30m)

Please feel free to signup the agenda slot by commenting Below.

### Video recordings

https://youtu.be/GNVSOgZ7g_Y

**Comment by xinbenlv** [comment]
Please add to the agenda for an intro to [ERC-5453 Endorsement](https://eips.ethereum.org/EIPS/eip-5453)

**Comment by sullof** [comment]
I may talk about [EIP6982 Efficient Default Lockable NFTs](https://github.com/ethereum/EIPs/blob/82372cbae88746c496ce1fbd4524862606de7421/EIPS/eip-6982.md) and [EIP6454](https://eips.ethereum.org/EIPS/eip-6454) which move in the same space, but with different targets in mind.

**Comment by socathie** [comment]
We would like to request to present for the peer review slot for [EIP-7007 zkML AIGC NFTs](https://github.com/ethereum/EIPs/pull/7007).

**Comment by jwindawi** [comment]
We would like to request to present [EIP-6900](https://github.com/ethereum/EIPs/pull/6900) in the peer review section.
