### ISSUE TITLE
(Current) 2024-03-21 (E1S2) AllERCDevs Agenda Thursday (EMEA friendly time)

### ISSUE THREAD

**Issue by thatIslily** [ercref/AllERCDevs#17]
[![ERCRef Discord](https://badgen.net/discord/members/XZ7kXc52rD)](https://discord.gg/XZ7kXc52rD)

2024-03-21 UTC 1700-1759 Thursday, find [your time zone here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=7th+AllERCDevs&iso=20240321T17&p1=1440&ah=1)

## Meeting Links

Google Meet https://meet.google.com/pzv-hcke-osm

## Agenda
- Welcome back to the season 2 of AllERCDevs by @xinbenlv 5'

- [ERC-7651 Fractionally Represented Non-Fungible Token](https://ethereum-magicians.org/t/erc-7651-fractionally-represented-non-fungible-token/19176) 10' by @0xAcme
- [ERC-7631 Dual Nature Token Pair](https://ethereum-magicians.org/t/erc-7631-dual-nature-token-pair/18796) 10' by @Vectorized
- [ERC-7531 Resolving Staked ERC-721 Ownership Recognition](https://ethereum-magicians.org/t/eip-7531-resolving-staked-erc-721-ownership-recognition/15967) 10' by @sullof
- (maybe) [Smart Account dApp Permissions](https://blog.danfinlay.com/a-post-smart-account-dapp-permissions-flow/) 10' by @danfinlay
- Discussion: A ProtocolGuild equivalent to ERC contributors?

Other invitees: @fulldecent, @amxx, @frangio

Meeting hosts: @xinbenlv, @thatIslily

**Comment by sullof** [comment]
I can talk about [EIP-7531 Resolving Staked ERC-721 Ownership Recognition](https://ethereum-magicians.org/t/eip-7531-resolving-staked-erc-721-ownership-recognition/15967)

**Comment by xinbenlv** [comment]
Added to the agenda, thank you @sullof

**Comment by fulldecent** [comment]
For agenda: https://github.com/ethereum/EIPs/issues/8284

---

This issue says it is the first meeting. But it is not listed at https://github.com/ercref/AllERCDevs as a future meeting. And that page lists 12 past meetings

**Comment by xinbenlv** [comment]
Fixing it

**Comment by xinbenlv** [comment]
> For agenda: [ethereum/EIPs#8284](https://github.com/ethereum/EIPs/issues/8284)
> 
> This issue says it is the first meeting. But it is not listed at https://github.com/ercref/AllERCDevs as a future meeting. And that page lists 12 past meetings

Thank you! Updated the readme!

**Comment by xinbenlv** [comment]
Thanks everyone who came and contributed:

In this S2E1 AllERCDevs session, we delved into ERC-7651, ERC-7631, and ERC-7531 and DApp permission flow by Dan Finlay.

The ERC-7651 (https://eips.ethereum.org/EIPS/eip-7651) was introduced by @0xAcme, a spec for fractionally represented NFTs within a single contract, addressing issues of liquidity and fractional representation in the NFT space. The discussion led to @fulldecent (William Entriken) expressing concerns about creating a new ecosystem and the compatibility challenges with existing infrastructures like OpenSea. William pushed for a strong coalition to move such an ambitious standard forward.

@Vectorized (Vectorized) discussed ERC-7631 (https://eips.ethereum.org/EIPS/eip-7631), a standard for a dual nature token pair linking ERC-20 and ERC-721 tokens while preserving full standard compliance. Francesco Sullo provided feedback, encouraging consideration of a more interconnected approach between contracts to enhance compatibility.

@sullof(Francesco Sullo) presented ERC-7531 (https://eips.ethereum.org/EIPS/eip-7531) a proposal to resolve staked ERC-721 ownership, allowing holders to retain certain rights while their NFTs are staked. This sparked a dialogue about the desirability of such features from projects like Bored Ape Yacht Club and others in the gaming industry. Francisco Giordano suggested an opt-in feature for tokens to declare different types of rights.

The session also featured insights from @danfinlay (Dan Finlay) on an early draft of DApp permissions flow (https://blog.danfinlay.com/a-post-smart-account-dapp-permissions-flow/), highlighting the potential for a new standard that could make user interactions with DApps more secure. This led to a discussion on the importance of specifying how wallets should present authorization information to users. @ZainanZhou also suggested to share the conversation in other venues such as #AllWalletDevs ran by @_SamWilsn_ and #EthDebug ran by @gnidan that cares about readability of what's being signed in a wallet.

We appreciated contributions from @ZainanZhou, @fulldecent, @0xAcme, @Vectorized, @sullof, @frangio, @Amxx , and @danfinlay, as well as all participants who engaged in the conversations.

Special thanks to @alohalily668 (Lily Wang) for facilitating the session and to @EthMagicians, @EthCatHerders, @EIPfun, and @Namefi_io for supporting #AllERCDevs. 

Raw full transcription and recordings can be found: https://app.fireflies.ai/view/AllERCDevs-S2E1::4XAWqjTbTDovO9rS and later on https://github.com/ercref/AllERCDevs

We Look forward to the next session and the continued collaboration to shape the future of Ethereum standards: 2024-04-02 Tuesday UTC 2300

You can sign up relevant topic you want to bring at this agenda issue: https://github.com/ercref/AllERCDevs/issues/19

Spoiler alert: one of the next topics will be @z0age to share the @opensea's latest #Seaport contract v1.6 and its hooks architect.

DM me if you want a calendar invite as a reminder.
