### ISSUE TITLE
[Past] S2E3 AllERCDevs Agenda April 18th UTC1700 EMEA friendly time

### ISSUE THREAD

**Issue by xinbenlv** [ercref/AllERCDevs#21]
[![ERCRef Discord](https://badgen.net/discord/members/XZ7kXc52rD)](https://discord.gg/XZ7kXc52rD)

2024-04-18 UTC 1700-1759 Thursday, find [your time zone here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=7th+AllERCDevs&iso=20240418T17&p1=1440&ah=1)

## Meeting Links

Google Meet https://meet.google.com/pzv-hcke-osm

## Agenda
- Introducing AllERCDevs and speakers / reviewers today by @xinbenlv
- [Intro to EthDebug](https://notes.ethereum.org/@gnidan/BJQek0CeC) by 10min intro + 5min Q&A @gnidan
  - https://gist.github.com/gnidan/b1890c68c8e0825d4a699929ccb2018e
- [5792](https://ethereum-magicians.org/t/eip-5792-wallet-function-call-api/11374/35) - wallet_ RPCs for dapps to send multiple userOps to a 4337 wallet 10min intro + 5min Q&A by @bumblefudge 
- [TBC] ERC-2535 adoption by @mudgen and/or @DiamondSwapTeam 10min

Invited peer reviewers: @ricmoo, @fulldecent, @frangio ,  @pedrouid, @vectorized

Meeting hosts: @xinbenlv, @thatIslily, 

## Recordings and Notes
- Summary Tweet: https://x.com/ZainanZhou/status/1781633462102786249
- Raw Notes: https://app.fireflies.ai/view/AllERCDevs-S2E3::3HMapZ46o1B7y32l
- Video Recordings: https://www.youtube.com/watch?v=Me2CQIahJ9E

**Comment by bumblefudge** [comment]
If anyone is curious about the various 4337-related EIPs flying around at the moment, I could maybe answer questions from dapp devs about:
* [7677](https://ethereum-magicians.org/t/erc-7677-paymaster-web-service-capability/19530/3) - dapps declaring paymaster intentions to 4337 wallets 
* [7679](https://ethereum-magicians.org/t/erc-7679-useroperationbuilder-a-common-onchain-interface-for-dapps-to-interact-with-4337-wallets/19547) - dapps constructing UserOps with the support of some new 4337 helper functions, and
* [5792](https://ethereum-magicians.org/t/eip-5792-wallet-function-call-api/11374/35) - wallet_ RPCs for dapps to send multiple userOps to a 4337 wallet

**Comment by xinbenlv** [comment]
I would love to hear 5792, but it's your call. Putting down 5792 as agenda. Feel free to request if you prefer a different one @bumblefudge

**Comment by xinbenlv** [comment]
```
Vectorized
9:23 PM
mstore(0x00, key)
mstore(0x20, x.slot)
keccak256(0x00, 0x40)
i think vyper switches the order of x.slot and key?
g. nicholas d'andrea
9:24 PM
audio permissionssss
You
9:25 PM
7677 - dapps declaring paymaster intentions to 4337 wallets
7679 - dapps constructing UserOps with the support of some new 4337 helper functions, and
5792 - wallet_ RPCs for dapps to send multiple userOps to a 4337 wallet
https://github.com/ercref/AllERCDevs/issues/21
You
9:28 PM
https://ethereum-magicians.org/t/erc-7677-paymaster-web-service-capability/19530/3
https://ethereum-magicians.org/t/erc-7679-useroperationbuilder-a-common-onchain-interface-for-dapps-to-interact-with-4337-wallets/19547
https://ethereum-magicians.org/t/eip-5792-wallet-function-call-api/11374/35
Francisco Giordano
9:29 PM
ERC4337 EntryPoint does not have an owner , if this is the question
Pedro Gomes
9:36 PM
no mic today sorry
Bumblefudge von CASA
9:39 PM
is there a discussion thread on snapshot about hte multichain stuff specifically?
Bumblefudge von CASA
9:40 PM
CASA supports chainId 0 now :D 
https://github.com/ChainAgnostic/namespaces/pull/107/files
GriffGreen's PR got moved from /caips to /namespaces
g. nicholas d'andrea
9:42 PM
question if there's time: does this current reverse registration work address contracts having reverse names?
Pedro Gomes
9:45 PM
EIP-5003 will solve this
g. nicholas d'andrea
9:45 PM
oh nice!
yeah I know nick.eth had said at some point that y'all were looking into a solution with contracts defining owner
but yeah 5003 looks much better
Pedro Gomes
9:46 PM
turn all EOAs into SCAs
Bumblefudge von CASA
9:48 PM
https://eips.ethereum.org/EIPS/eip-173 ?
https://www.rareskills.io/post/eip-1167-minimal-proxy-standard-with-initialization-clone-pattern ?
Prem Makeig
9:53 PM
https://github.com/ensdomains/docs/blob/evm-reverse-resolution/ens-improvement-proposals/ensip-17-evmchain-reverse-resolution.md
```
