### ISSUE TITLE
[Past] 4th AllERCDevs Agenda (EU / US Friendly) Thursday, 2023-06-29 15:00 UTC

### ISSUE THREAD

**Issue by xinbenlv** [ercref/AllERCDevs#5]
The time of event will be 

*2023-06-29 UTC 1500-1559 Thursday*, [find your timezone here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=4th+AllERCDevs&iso=20230629T15&p1=1440&ah=1)

The event will be hosted on Zoom, a link will be posted on "all-erc-devs" channel on this [Discord Server](https://discord.gg/2arW34S6J7)

Agenda will be updated and please feel free to comment to signup your agenda items.

### Main Session (1h)

1. [ ] (15-20min) *Featured Talk*: 
- ERC-1363 Payable Tokens by @vittominacori
2. (10min) *Demo Show & Tell* (5-10min per slot)
- https://chainrelay.com/ and https://github.com/chain-names/ethereum-contracts/tree/main/ERC-721 by @evbots

4. (30min) *ERC Peer Review Requests* (5-10min per slot)
- [TCTC](https://github.com/kofujimura/TCTC) by @kofujimura

5. Special Topic
- ERC to be removed from EIP, your feedback?
- Any interest in signing up for peer reviewer?

### Social Chat for ERCers
What do you find interesting last week? It doesn't have to be related to ERC.

## Meeting Link

Zoom Meeting Link: https://us06web.zoom.us/j/88694529887?pwd=NDRWYXlhejBvcXFVSzEzRFluT0Jmdz09

Meeting ID: 886 9452 9887
Passcode: 338406

### Video
https://youtu.be/NfUvUL-lAco

### Summary
The meeting involved Zainan Victor Zhou, Evan Botello, Pooja Ranjan, Ko Fujimura, and vittominacori discussing Ethereum and ERC standards, focusing on ERC 1363, a payable token standard proposed by vittominacori. The standard allows users to perform another action after a transfer in a single transaction. The conversation also covered a new platform that simplifies the deployment of smart contracts, Ko Fujimura's first ERC proposal, TCTC, and the proposal to move ERCs out from the EIP repository.

### Full Transcription
https://app.airgram.io/7065496599555735553/share/b49748fa168d11eeb49b0a2cbd030b4d?from=A91fc19caf6ac11eda1a80a2cbd030b4d-7065496599555735553

**Comment by kofujimura** [comment]
I would like to present [TCTC](https://github.com/kofujimura/TCTC), which is a new scheme of access control.

**Comment by kofujimura** [comment]
2023-06-29 UTC 1500-1559 Thursday, which translates to
- 08:00-08:59 on 2023-06-29 Thursday in US Pacific Time.
- 11:00-11:59 on 2023-06-29 Thursday in US Eastern Time.
- 23:00-23:59 on 2023-06-29 Thursday in Singapore.

**Comment by xinbenlv** [comment]
@kofujimura thank you, I updated it
